genre/urls.py
from django.urls import path
from . import views

app_name = 'genre'

urlpatterns = [
    path('',views.action,name = 'action'),
    path('comedy',views.comedy,name = 'comedy'),
    path('drama',views.drama,name = 'drama'),
    path('thriller',views.thriller,name = 'thriller'),
    path('adventure',views.adventure,name = 'adventure'),
    path('romance',views.romance,name = 'romance'),
    path('crime',views.crime,name = 'crime'),
    path('sciencefiction',views.sciencefiction,name = 'sciencefiction'),

]

movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('',views.index, name='index'),
    path('details/<int:id>', views.details, name='details'),
    path('search', views.search, name='search'),
    # path('recommendation/<str:title>',views.recommendation,name='recommendation'),
    # path('top-movies/',views.top_movies,NameError='top-movies'),
    # path('top-series/',views.top_series,NameError='top-series'),
    
]

mrs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

def index(request):
    return redirect('movies:index')

urlpatterns = [
    path('',index),
    path('movies/', include('movies.urls')),
    path('questions/', include('questions.urls')),
    path('genre/', include('genre.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('search/', include('searchData.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('',views.index,name = 'index'),
    

   
]

movies/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# def post_image(instance,filename):
#     return f'movies/poster/{filename}'


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=200)
    releasedDate = models.CharField(max_length=200)
    duration = models.CharField(max_length=200)
    genre = models.CharField(max_length=100,null=True)
    rating = models.FloatField(
                default=1,
                validators=[MaxValueValidator(10), MinValueValidator(1)]
    )
    description = models.TextField()
    org_language = models.CharField(max_length=200,null=True)
    director = models.CharField(max_length=50,null=True)
    cast = models.CharField(max_length=100,null=True)
    tags = models.CharField(max_length=1000,null=True)
    trailer = models.URLField(null=True)

    

    

    def __str__(self):
        return self.title
    # poster = models.ImageField(upload_to=post_image

movies/views.py
from traceback import print_tb
from django.http import request
from django.shortcuts import render
import pickle
import pandas as pd
import requests

from movies.models import Movie

# Create your views here.
from .models import Movie

def index(request):
    movies = Movie.objects.all()
    # url = "https://api.themoviedb.org/3/movie/top_rated?api_key=5578e593eff67be13a5e7e2ae5074824&language=en-US&page=1"
    # top_rated = requests.get(url)
    # top_rated = top_rated.json()
    # top_rated_title = []
    # for i in top_rated:
    #         top_rated_title.append(top_rated['original_title'])
    poster = []
    for i in movies:
        poster.append(fetch_poster(i.id))

    result = list(zip(movies,poster))
    context = {'result':result}
    return render(request,'movies/index.html',context)

def search(request):
    movies = Movie.objects.all()
    poster = []
    for i in movies:
        poster.append(fetch_poster(i.id))
    result = list(zip(movies,poster))
    if request.method == "POST":
      searched = request.POST['searched']  
      searchedmovie = Movie.objects.get(title=searched)
      postersearch = fetch_poster(searchedmovie.id)
      trailersearch = fetch_trailer(searchedmovie.id)
      data = recommendation(searchedmovie.title)
      context = {
        'movies':movies,
        'result':result,
        'searched':searched,
        'searchedmovie':searchedmovie,
        'postersearch':postersearch,
        'trailersearch':trailersearch,
        'data':data
        }
      return render(request,'movies/details.html',context)
    else:
      movie = Movie.objects.get(id=id)
      context = {'movie':movie}
      return render(request,'movies/index.html',context)       



def details(request, id):
    movies = Movie.objects.all()
    poster = []
    for i in movies:
        poster.append(fetch_poster(i.id))
    result = list(zip(movies,poster)) 
    searchedmovie =  Movie.objects.get(id=id)
    postersearch = fetch_poster(searchedmovie.id)
    trailersearch = fetch_trailer(searchedmovie.id)
    data = recommendation(searchedmovie.title)
    context = {
     'movies':movies,
     'result':result,
    #  'searched':searched,
     'searchedmovie':searchedmovie,
     'postersearch':postersearch,
     'trailersearch':trailersearch,
     'data':data
     }
    return render(request,'movies/details.html',context)    



#Recommendated Movies    
# movies_dict = pickle.load(open('movie_list.pkl','rb'))
# movies = pd.DataFrame(movies_dict)
# similarity = pickle.load(open('similarity.pkl','rb'))



def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US".format(movie_id)
    data = requests.get(url)
    data = data.json()
    poster_path = data['poster_path']
    full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    return full_path

def fetch_trailer(movie_id):
    url = "http://api.themoviedb.org/3/movie/{}/videos?api_key=5578e593eff67be13a5e7e2ae5074824".format(movie_id)
    data = requests.get(url)
    data = data.json()
    # trailer_path = data['key']
    # full_path = "https://www.youtube.com/watch?v=" + trailer_path
    # type = "Trailer"
    for da in data['results']:
        if da["type"] == "Trailer":
            trailer_path = da['key']
            full_path = "https://www.youtube.com/embed/" + trailer_path
    return full_path



#Recommendated Movies    
movies_dict = pickle.load(open('movie_list.pkl','rb'))
movies = pd.DataFrame(movies_dict)
similarity = pickle.load(open('similarity.pkl','rb'))


def recommendation(title):
    movie = Movie.objects.get(title=title)
    # context = {'movie':movie} 
    index=movies[movies['title']== title].index[0]
    similarity_score=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x : x[1])
    
    res = []
    resid = []
    recommended_movie_posters = []
    for i in similarity_score[1:6]:
        movie_id = movies.iloc[i[0]].movie_id
        recommended_movie_posters.append(fetch_poster(movie_id))
        res.append(movies.iloc[i[0]].title)
        resid.append(movie_id)
        # print(movie_id)
        # ress.append(movies.iloc[i[0]].movie_id)
    
    result = zip(res,recommended_movie_posters,resid)
    # data = {
    #     # 'res':res,
    #     'result':result,
    #     # 'recommended_movie_posters':recommended_movie_posters,
    #     'movie':movie,
    # }  
    return result











  
  



 
  

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static%}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CINEPHILE - Movie Recommendation System</title>
	
	<link rel="shortcut icon" href="{% static 'movies/img/homepage images/index.png'%}">

    <!--------------------------------------------- Bootsrap CDN --------------------------------------------------->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!--------------------------------------------- Jquery CDN --------------------------------------------------->
 	 <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

	<!--------------------------------------------- Slick  CDN --------------------------------------------------->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	
	<!---------------------------------------------Google Font --------------------------------------------------->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Montagu+Slab:wght@600&display=swap" rel="stylesheet">

  <!---------------------------------------------Font Awesome CDN--------------------------------------------------->

  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
	
	<!---------------------------------------------Custom Styling--------------------------------------------------->
	<link rel="stylesheet" type="text/css" href="{% static 'movies/css/style.css'%}">

  
  
  

 	

</head>
<body>
	
	<!------------------------------------------------Navbar-------------------------------------------->
        <header>
            <nav id="navbar_top"s class="navbar fixed-top navbar-expand-lg navbar-light">
              <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'movies:index'%}"><img src="{% static 'movies/img/homepage images/logo.png'%}" alt="logo"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      
                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'movies:index'%}">Home</a>
                    </li>
                  
                    <!-- <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'questions:index'%}">Suggest a Movie</a>
                    </li> -->
                    <li class="nav-item">
                      <a class="nav-link" href="#popularmovies">Popular Movies</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#topratedmovies">Top Rated Movies</a>
                    </li>
      
                    <!-- Dropdown Menu -->
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Browse by Genre
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'genre:action'%}">Action</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:comedy'%}">Comedy</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:drama'%}">Drama</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:thriller'%}">Thriller</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:adventure'%}">Adventure</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:romance'%}">Romance</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:crime'%}">Crime</a></li>
                        <li><a class="dropdown-item" href="{% url 'genre:sciencefiction'%}">Science Fiction</a></li>
            
                      </ul>
                    </li>
                  </ul>
      
                   <!-- Search Bar -->
                   <form class="d-flex" action="{% url 'movies:search'%}" method="POST">
                     {% csrf_token %}
                    <input list="movies" class="form-control me-2 search" type="search" placeholder="Search Movie..." aria-label="Search" name="searched" style="width: 150%;">
                    <datalist id="movies">
                          {% for movie,poster in result %}
                              <option value="{{movie.title}}">
                          {% endfor %}	
                    </datalist>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                  
                </div>
              </div>
            </nav>
          </header>
      
      
         
      
      


	{% block content %}
    
    
    {% endblock%}


    <!------------------------------------------------Footers-------------------------------------------->

	<div id="footer-wrapper">
			
		<footer>
			COPYRIGHT © 2021 CINEPHILE	

		</footer>

	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg=="
	 crossorigin="anonymous" referrerpolicy="no-referrer"></script>

	 <script type="text/javascript">
		 $('.slider').slick({
  dots: true,
  infinite: true,
  speed: 200,
  slidesToShow: 4,
  slidesToScroll: 1,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
});
	 </script>

</body>
</html>

movies/templates/movies/details.html
{% extends 'movies/base.html' %}
{% load static%}


{% block content%}
<link rel="stylesheet" type="text/css" href="{% static 'searchData/css/search.css'%}">


<div class="container">
    <div class="row top-desc">
            <div class="col-6">
                <h1>{{searchedmovie.title}}</h1>
                    <p>Movie  |  {{searchedmovie.releasedDate}}  |  {{searchedmovie.duration}}min</p>           
            </div>
            <div class="col-3">
                <h4>IMDb Rating</h4>
                <div class="social-icon"   >
                    <i class="fas fa-star"></i>
                <span>{{searchedmovie.rating}}</span>
                 </div>
                
            </div>
            <div class="col-3">
                POPULARITY
            </div>
    </div>
    <hr>


    <div class="row">
        <div class="col-4" id="search-img">
            <img src="{{postersearch}}"  alt="">
        </div>
        <div class="col-8" id="search-video">
            <iframe width="100%" height="400px" src="{{trailersearch}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            
        </div>
      </div>

      

    <div class="row search-detail"> 
        <div class="col-8">
            <h6 class="genre-btn">Comedy</h6>
            
            {% for i  in searchedmovie.genre  %}   
                {{i}}  
            {% endfor %}	

            <p>{{searchedmovie.description}}</p>
            <hr>
        </div>
        <div class="col-4">

        </div>
    </div>

    <div class="row stars">
         
         <ul>
            <a href="#">Stars</a>
            <a href="#">{{searchedmovie.director}}</a>
            <a href="#">Raghuvir Yadav</a>
            <a href="#">Chandan Roy</a>
         </ul>
    </div>
    <hr>

    <div class="row top-cast">
        <h2>| Top Cast</h2>
        <div class="row">
            <div class="col-1">
                <img src="{% static 'searchData/img/test.png'%}" alt="">
            </div>
            <div class="col-5">
                <a href="#">Jitendra Kumar</a>
                    <p>as Abhishek Tripathi (Gram Sachiv)</p>
            </div>
            <div class="col-1">
                <img src="{% static 'searchData/img/test.png'%}" alt="">
            </div>
            <div class="col-5">
                <a href="#">Jitendra Kumar</a>
                    <p>as Abhishek Tripathi (Gram Sachiv)</p>
            </div>
          </div>

          <div class="row">
            <div class="col-1">
                <img src="{% static 'searchData/img/test.png'%}" alt="">
            </div>
            <div class="col-5">
                <a href="#">Jitendra Kumar</a>
                    <p>as Abhishek Tripathi (Gram Sachiv)</p>
            </div>
            <div class="col-1">
                <img src="{% static 'searchData/img/test.png'%}" alt="">
            </div>
            <div class="col-5">
                <a href="#">Jitendra Kumar</a>
                    <p>as Abhishek Tripathi (Gram Sachiv)</p>
            </div>
          </div>
    </div>

    <div class="row storyline">
        <h2>| Storyline</h2>
        <p>{{searchedmovie.description}}</p>
    </div>


    <div class="row">
        <h2>| Details</h2>
        <hr>
            <div class="col-6">
                <p class="detail-title"><span>Release date </span> 
            </div>
        
            <div class="col-6">
                {{searchedmovie.releasedDate}}</p>
            </div>
        <hr>

        <div class="col-6">
            <p class="detail-title"><span>Language </span> 
        </div>
    
        <div class="col-6">
            {{searchedmovie.org_language}}</p>
        </div>
        <hr>

        <div class="col-6">
            <p class="detail-title"><span>Duration </span> 
        </div>
    
        <div class="col-6">
            {{searchedmovie.duration}}min</p>
        </div>
        <hr>

        <div class="col-6">
            <p class="detail-title"><span>Director </span> 
        </div>
    
        <div class="col-6">
            {{searchedmovie.director}}</p>
        </div>
        <hr>


    </div>

  </div>
  <div class="popularcontainer" id="topratedseries">
   
        <h2>| Recommended</h2>
        <div class="movitem slider">
            {% for i,j,k in data %}
            <a href="{% url 'movies:details' k %}" style="text-decoration: none;"> 
            <div class="card" style="width: 18rem;">
                <img src="{{j}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <!-- {{k}} -->
                <h5 class="card-title">{{i}}</h5>
                </div>
              </div>
            </a>
              {% endfor %}	      
        </div>

 </div>

</div>

<!-- {% for i,j in data %}
   
    <h3 class="card-title">{{i}}</h3>
    <img src="{{j}}" alt="" height="300" width="200">
    
{% endfor %} -->

  

{% endblock %}

movies/templates/movies/index.html
{% extends 'movies/base.html '%}
{% load static%}

{% block content %}


	<!------------------------------------------------Carousel page-------------------------------------------->
		
	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-inner">
		  <div class="carousel-item active">
			<img src="{% static 'movies/img/homepage images/CinePhile (1).png'%}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'movies/img/homepage images/2.jpg'%}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'movies/img/homepage images/CinePhile.png'%}" class="d-block w-100" alt="...">
		  </div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  <span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  <span class="visually-hidden">Next</span>
		</button>
	  </div>


	<!------------------------------------------------Featured Movies-------------------------------------------->
	
	<div class="popularcontainer" id="popularmovies">
		<h1>Featured Movies</h1>

		
			<div class="movitem slider">
				{% for movie,poster in result|slice:"40:48" %}
				<a href="{% url 'movies:details' movie.id %}" style="text-decoration: none;">
				<div class="card" style="width: 18rem;">
					<img src="{{poster}}" class="card-img-top" alt="...">
					<div class="card-body">
						<div class="social-icon">
							<i class="fas fa-star"></i>
						<span>{{movie.rating}}</span>
						</div>
						<h5 class="card-title">{{movie.title}}</h5>
					</div>
				  </div>
				</a>
				  {% endfor %}				  
			</div>	  

</div>

			<hr style="margin:0;">
				 
			<!------------------------------------------------Top Rated Movies-------------------------------------------->
			<div class="popularcontainer" id="#topratedmovies">
				<h1>Top Rated Movies</h1>
		
				
					<div class="movitem slider">
						{% for movie,poster in result %}		
							{% if movie.rating > 7 %}					
								<a href="{% url 'movies:details' movie.id %}" style="text-decoration: none;"> 
										<div class="card" style="width: 18rem;">
											<img src="{{poster}}" class="card-img-top" alt="...">
											<div class="card-body">
												<div class="social-icon">
													<i class="fas fa-star"></i>
												<span>{{movie.rating}}</span>
												</div>
												<h5 class="card-title">{{movie.title}}</h5>
											</div>
										</div>
								</a>
							{% endif %}
						{% endfor %}	
									  
					</div>	  
		
		</div>
	
		
			
{% endblock%}

movies/templates/movies/recommendation.html
{{movie.title}}
{{movie.id}}
{% for i,j in result %}
   
    <h3 class="card-title">{{i}}</h3>
    <img src="{{j}}" alt="" height="300" width="200">
    
{% endfor %}